app:
  host: finance-app.com
  debug: True
  default_currency: USD
database:
  file_path: data/db.sqlite3
navbar:
  SpareBank1: https://www.sparebank1.no/ostlandet/nettbank-privat/oversikt
  Chase: https://secure05b.chase.com/web/auth/dashboard#/dashboard/accounts/summary/dda;params=dda,257633572
  Wealthfront: https://www.wealthfront.com/dashboard
  Optum HSA: https://account.optumbank.com/account
  Siemens Savings: https://leplb0700.upoint.alight.com/web/siemens/home?linkId=PRTL_DIRECT&technicalNameForLink=PRTL_DIRECT&userFriendlyNameForLink=Home&domain=Ben-CM&baseClientIndicator=Base
  Marcus: https://www.marcus.com/us/en/login